### ISSUE TITLE
can you add lib folder for saas kit

### ISSUE THREAD

**Issue by spellboundodoo** [xAlphaOmega/Odoo_Addons#1]
hi can you add lib folder for saas kit

**Comment by xAlphaOmega** [comment]
I'm not sure what you mean lib folder. Please explain.

**Comment by spellboundodoo** [comment]
> I'm not sure what you mean lib folder. Please explain.

as you have push module for odoo saas kit it has lib folder under static folder
but in your git it's not found. 
because may be in your gitignor lib folder is not allow.

as you have push that complete module not push what define inside gitignore that is not committed

**Comment by spellboundodoo** [comment]
> > I'm not sure what you mean lib folder. Please explain.
> 
> as you have push module for odoo saas kit it has lib folder under static folder
> but in your git it's not found.
> because may be in your gitignor lib folder is not allow.
> 
> as you have push that complete module not push what define inside gitignore that is not committed

see line number 61 on this file
https://github.com/xAlphaOmega/Odoo_Addons/blob/master/.gitignore

remove lib and then push it again

if you will do it it's very help full for me.

**Comment by xAlphaOmega** [comment]
This is my private collection, I'm new to GitHub and using it. I have done ask you asked. Make sure to visit the company after testing to ensure you purchase the module.
